<?php
/**
 * Admin controller class
 * Creates main menu and submenus for admin area
 *
 * @package NativeCustomFields
 * @subpackage Presentation\Admin\Controllers
 * @since 1.0.0
 */

namespace NativeCustomFields\Presentation\Admin\Controllers;

use Exception;
use NativeCustomFields\Common\Constants;
use NativeCustomFields\Common\Helper;
use NativeCustomFields\Services\FieldService;

defined('ABSPATH') || exit;

/**
 * Admin controller class.
 */
final class AdminController
{

	/**
	 * Field service.
	 *
	 * @var FieldService
	 */
	private FieldService $fieldService;

	/**
	 * Constructor.
	 *
	 * @param FieldService $fieldService Field service.
	 */
	public function __construct(FieldService $fieldService)
	{

		// Inject dependencies
		$this->fieldService = $fieldService;

		// Register hooks
		add_action('admin_enqueue_scripts', [$this, 'enqueueScripts']);
		add_action('admin_enqueue_scripts', [$this, 'enqueueStyles']);
		add_action('customize_controls_enqueue_scripts', [$this, 'enqueueScripts']);
		add_action('customize_controls_enqueue_scripts', [$this, 'enqueueStyles']);
		add_action('admin_menu', [$this, 'addMenu']);
		add_action('admin_menu', [$this, 'addSubMenus']);
	}

	/**
	 * Enqueue scripts for the admin area
     *
	 * @return void
	 * @since 1.0.0
	 */
	public function enqueueScripts(): void
	{
		// Enqueue WordPress media library (required for wp.media / MediaLibraryField)
		wp_enqueue_media();

		// Enqueue script for admin area
		$asset_file = require NATIVE_CUSTOM_FIELDS_PATH . '/build/admin/index.asset.php';
		wp_enqueue_script(
			'native-custom-fields',
			NATIVE_CUSTOM_FIELDS_URL . '/build/admin/index.js',
			$asset_file['dependencies'],
			$asset_file['version'],
			true
		);

		// Localize script for rest api and ajax actions
		$localize_data = apply_filters('native_custom_fields_localize_data', [
			'nonce'           => wp_create_nonce('native_custom_fields'),
			'assets_url'      => NATIVE_CUSTOM_FIELDS_URL . '/includes/Presentation/Admin/Assets/',
			'rest_url'        => esc_url_raw(rest_url()),
			'ajax_url'        => esc_url_raw(admin_url('admin-ajax.php')),
			'admin_url'       => esc_url_raw(admin_url()),
			'site_url'        => esc_url_raw(site_url()),
			'field_types'     => $this->fieldService->getFieldTypes(),
			'container_types' => $this->fieldService->getContainerTypes(),
			'dashboard_items' => $this->fieldService->getDashboardItems(),
		]);

		wp_localize_script('native-custom-fields', 'nativeCustomFieldsData', $localize_data);
	}

	/**
	 * Enqueue styles for the admin area
     *
	 * @return void
	 * @since 1.0.0
	 */
	public function enqueueStyles(): void
	{
		// Enqueue styles for admin area
		wp_enqueue_style(
			'native-custom-fields',
			NATIVE_CUSTOM_FIELDS_URL . '/build/admin/index.css',
			['wp-components'],
			Constants::VERSION
		);
	}

	/**
	 * Add a menu for the plugin
     *
	 * @return void
	 * @since 1.0.0
	 */
	public function addMenu()
	{
		add_menu_page(
			esc_html__('Native Custom Fields Menu', 'native-custom-fields'),
			esc_html__('Native Custom Fields', 'native-custom-fields'),
			'manage_options',
			'native-custom-fields',
			[$this, 'renderDashboard'],
			NATIVE_CUSTOM_FIELDS_URL . '/includes/Presentation/Admin/Assets/img/ncf_icon.png',
		);
	}

	/**
	 * Render HTML output for dashboard
     *
	 * @return void
	 * @since 1.0.0
	 */
	public function renderDashboard(): void
	{
		ob_start();
		try {
			include Constants::INCLUDES_PATH . 'Presentation/Admin/Views/admin-dashboard-page.php';
			echo ob_get_clean(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Output is generated by a trusted view template with proper escaping.
		} catch (Exception $e) {
			ob_end_clean();
		}
	}

	/**
	 * Add submenus for the plugin
     *
	 * @return void
	 * @since 1.0.0
	 */
	public function addSubMenus()
	{

		//Post Meta Page Builder
		add_submenu_page(
			'native-custom-fields',
			__('Post Type & Post Meta Fields Builder', 'native-custom-fields'),
			__('Post Types', 'native-custom-fields'),
			'edit_posts',
			'native-custom-fields-post-type-builder',
			[$this, 'renderPostMetaBuilderPage'],
		);

		//Term Meta Page Builder
		add_submenu_page(
			'native-custom-fields',
			__('Taxonomies & Term Meta Fields Builder', 'native-custom-fields'),
			__('Taxonomies', 'native-custom-fields'),
			'manage_categories',
			'native-custom-fields-taxonomy-builder',
			[$this, 'renderTermMetaBuilderPage'],
		);

		//User Meta Page Builder
		add_submenu_page(
			'native-custom-fields',
			__('User Meta Fields Builder', 'native-custom-fields'),
			__('User Meta', 'native-custom-fields'),
			'manage_categories',
			'native-custom-fields-user-meta-builder',
			[$this, 'renderUserMetaBuilderPage'],
		);

		//Options Page Builder
		add_submenu_page(
			'native-custom-fields',
			__( 'Options Page Builder', 'native-custom-fields' ),
			__( 'Options Pages', 'native-custom-fields' ),
			'manage_options',
			'native-custom-fields-options-page-builder',
			[ $this, 'renderOptionsBuilderPage' ]
		);
	}


	/**
	 * Render post meta builder page
	 *
	 * @return void
	 * @since 1.0.0
	 */
	public function renderPostMetaBuilderPage()
	{
		Helper::renderBuilderPage('native-custom-fields-post-meta-builder-wrapper');
	}

	/**
	 * Render term meta builder page
	 *
	 * @return void
	 * @since 1.0.0
	 */
	public function renderTermMetaBuilderPage()
	{
		Helper::renderBuilderPage('native-custom-fields-term-meta-builder-wrapper');
	}

	/**
	 * Render user meta builder page
	 *
	 * @return void
	 * @since 1.0.0
	 */
	public function renderUserMetaBuilderPage()
	{
		Helper::renderBuilderPage('native-custom-fields-user-meta-builder-wrapper');
	}

	/**
	 * Render the Options Page Builder page.
	 *
	 * @return void
	 * @since 1.0.5
	 */
	public function renderOptionsBuilderPage(): void {
		Helper::renderBuilderPage( 'native-custom-fields-options-page-builder-wrapper' );
	}
}
